import pulumi

from utils import fetch_public_ip, read_public_key
from network import create_network
from compute import create_service_account, create_instance
from agent import prepare_startup_script

config = pulumi.Config()
GCP_ZONE = config.get("zone") or "us-central1-a"
MACHINE_TYPE = config.get("machine_type") or "e2-medium"

# Ubuntu image for the compute instance, configurable via Pulumi config
UBUNTU_IMAGE = config.require("ubuntuImage")

# Read the SSH public key generated by the scenario runner
# The key path is set via Pulumi config by the scenario execution script
SSH_PUBLIC_KEY_PATH = config.require("publicKeyPath")
SSH_PUBLIC_KEY = read_public_key(SSH_PUBLIC_KEY_PATH)
SSH_USER = "cobra"

# Read custom labels from Pulumi config to apply to all GCP resources that support labeling
DEFAULT_LABELS = config.require_object("labels")

# Whether to include the Cortex XDR agent on the compute instance
INCLUDE_AGENT = config.get_bool("includeAgent") or False

# ---------------------------------------------------------------------------
# Networking
# ---------------------------------------------------------------------------
# Resolve the deployer's public IP and convert to /24 CIDR block
# NOTE: SSH access is restricted to the /24 CIDR block of the deployer's
# current public IP. The instance will only be accessible via SSH from that
# same IP range. If you run this from a different network later, you will
# need to update the firewall rule or redeploy.
deployer_ip = fetch_public_ip()
ssh_cidr = ".".join(deployer_ip.split(".")[:-1]) + ".0/24"
pulumi.log.warn(
    f"SSH access is restricted to {ssh_cidr}. "
    "The instance will only be accessible from this CIDR block. "
    "If you need access from a different network, update the firewall "
    "rule or redeploy from the desired network."
)

network, _firewall = create_network(ssh_cidr)

# ---------------------------------------------------------------------------
# IAM / Compute
# ---------------------------------------------------------------------------
service_account = create_service_account()

# ---------------------------------------------------------------------------
# Agent & Startup Script
# ---------------------------------------------------------------------------
startup_script, agent_exports = prepare_startup_script(
    include_agent=INCLUDE_AGENT,
    config=config,
    service_account=service_account,
    default_labels=DEFAULT_LABELS,
)

# ---------------------------------------------------------------------------
# Compute Instance
# ---------------------------------------------------------------------------
instance = create_instance(
    machine_type=MACHINE_TYPE,
    zone=GCP_ZONE,
    ubuntu_image=UBUNTU_IMAGE,
    network=network,
    service_account=service_account,
    ssh_user=SSH_USER,
    ssh_public_key=SSH_PUBLIC_KEY,
    startup_script=startup_script,
    default_labels=DEFAULT_LABELS,
)

# ---------------------------------------------------------------------------
# Exports
# ---------------------------------------------------------------------------
pulumi.export("Instance Name", instance.name)
pulumi.export("Instance ID", instance.id)
pulumi.export("Instance Zone", instance.zone)
pulumi.export("Instance Public IP", instance.network_interfaces[0].access_configs[0].nat_ip)
pulumi.export("Instance Private IP", instance.network_interfaces[0].network_ip)
pulumi.export("Instance Machine Type", instance.machine_type)
pulumi.export("Service Account Email", service_account.email)
pulumi.export("Network Name", network.name)
pulumi.export("SSH User", SSH_USER)
pulumi.export("Web App URL", instance.network_interfaces[0].access_configs[0].nat_ip.apply(
    lambda ip: f"http://{ip}:8080/ping?address="
))

for key, value in agent_exports.items():
    pulumi.export(key, value)
