import pulumi
import pulumi_gcp as gcp

from utils import fetch_public_ip, read_public_key
from network import create_network
from compute import create_sa_role_binding, create_instance
from agent import prepare_startup_script, prepare_startup_script_2

config = pulumi.Config()
GCP_ZONE = config.get("zone") or "us-central1-a"
MACHINE_TYPE = config.get("machine_type") or "e2-medium"

# Ubuntu image for the compute instance, configurable via Pulumi config
UBUNTU_IMAGE = config.require("ubuntuImage")

# Read the SSH public key generated by the scenario runner
# The key path is set via Pulumi config by the scenario execution script
SSH_PUBLIC_KEY_PATH = config.require("publicKeyPath")
SSH_PUBLIC_KEY = read_public_key(SSH_PUBLIC_KEY_PATH)
SSH_USER = "cobra"

# Read custom labels from Pulumi config to apply to all GCP resources that support labeling
DEFAULT_LABELS = config.require_object("labels")

# Whether to include the Cortex XDR agent on the compute instances
INCLUDE_AGENT = config.get_bool("includeAgent") or False

# ---------------------------------------------------------------------------
# Networking
# ---------------------------------------------------------------------------
# Resolve the deployer's public IP and convert to /24 CIDR block
# NOTE: SSH access is restricted to the /24 CIDR block of the deployer's
# current public IP. The instance will only be accessible via SSH from that
# same IP range. If you run this from a different network later, you will
# need to update the firewall rule or redeploy.
deployer_ip = fetch_public_ip()
ssh_cidr = ".".join(deployer_ip.split(".")[:-1]) + ".0/24"
pulumi.log.warn(
    f"SSH access is restricted to {ssh_cidr}. "
    "The instance will only be accessible from this CIDR block. "
    "If you need access from a different network, update the firewall "
    "rule or redeploy from the desired network."
)

network, _firewall = create_network(ssh_cidr)

# ---------------------------------------------------------------------------
# IAM / Service Accounts
# ---------------------------------------------------------------------------
service_account = gcp.serviceaccount.Account("cobra-scenario-9-sa",
    account_id="cobra-scenario-9-sa",
    display_name="Cobra Scenario 9 Service Account",
)
# Instance 1's SA needs serviceAccountUser & compute.editor to call setMetadata on instances
# running as a different service account (e.g. Instance 2).
create_sa_role_binding("sa-compute-editor", service_account, "roles/compute.editor")
create_sa_role_binding("sa-sa-user", service_account, "roles/iam.serviceAccountUser")

service_account_2 = gcp.serviceaccount.Account("cobra-scenario-9-sa-2",
    account_id="cobra-scenario-9-sa-2",
    display_name="Cobra Scenario 9 Service Account 2",
)
create_sa_role_binding("sa2-sa-admin", service_account_2, "roles/iam.serviceAccountAdmin")

# ---------------------------------------------------------------------------
# Agent & Startup Scripts
# ---------------------------------------------------------------------------
startup_script, agent_exports, agent_bucket, agent_object = prepare_startup_script(
    include_agent=INCLUDE_AGENT,
    config=config,
    service_account=service_account,
    default_labels=DEFAULT_LABELS,
)

startup_script_2 = prepare_startup_script_2(
    include_agent=INCLUDE_AGENT,
    service_account=service_account_2,
    agent_bucket=agent_bucket,
    agent_object=agent_object,
)

# ---------------------------------------------------------------------------
# Compute Instances
# ---------------------------------------------------------------------------
instance = create_instance(
    name="cobra-scenario-9-instance",
    machine_type=MACHINE_TYPE,
    zone=GCP_ZONE,
    ubuntu_image=UBUNTU_IMAGE,
    network=network,
    service_account=service_account,
    ssh_user=SSH_USER,
    ssh_public_key=SSH_PUBLIC_KEY,
    startup_script=startup_script,
    default_labels=DEFAULT_LABELS,
)

instance_2 = create_instance(
    name="cobra-scenario-9-instance-2",
    machine_type=MACHINE_TYPE,
    zone=GCP_ZONE,
    ubuntu_image=UBUNTU_IMAGE,
    network=network,
    service_account=service_account_2,
    ssh_user=SSH_USER,
    ssh_public_key=SSH_PUBLIC_KEY,
    startup_script=startup_script_2,
    default_labels=DEFAULT_LABELS,
)

# ---------------------------------------------------------------------------
# Exports
# ---------------------------------------------------------------------------
gcp_config = pulumi.Config("gcp")
pulumi.export("GCP Project", gcp_config.require("project"))

pulumi.export("Instance Name", instance.name)
pulumi.export("Instance ID", instance.id)
pulumi.export("Instance Zone", instance.zone)
pulumi.export("Instance Public IP", instance.network_interfaces[0].access_configs[0].nat_ip)
pulumi.export("Instance Private IP", instance.network_interfaces[0].network_ip)
pulumi.export("Instance Machine Type", instance.machine_type)
pulumi.export("Service Account Email", service_account.email)
pulumi.export("Network Name", network.name)
pulumi.export("SSH User", SSH_USER)
pulumi.export("Web App URL", instance.network_interfaces[0].access_configs[0].nat_ip.apply(
    lambda ip: f"http://{ip}:8080/ping?address="
))

pulumi.export("Instance 2 Name", instance_2.name)
pulumi.export("Instance 2 ID", instance_2.id)
pulumi.export("Instance 2 Zone", instance_2.zone)
pulumi.export("Instance 2 Public IP", instance_2.network_interfaces[0].access_configs[0].nat_ip)
pulumi.export("Instance 2 Private IP", instance_2.network_interfaces[0].network_ip)
pulumi.export("Instance 2 Machine Type", instance_2.machine_type)
pulumi.export("Service Account 2 Email", service_account_2.email)

for key, value in agent_exports.items():
    pulumi.export(key, value)
